.drone.yml
.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/models/user.rb
app/services/cognito/auth_user.rb
config/initializers/remote_authenticatable.rb
features/step_definitions/helper_steps.rb
features/step_definitions/sign_in_steps.rb
features/step_definitions/upload_steps.rb
features/support/login_helpers.rb
features/upload.feature
lib/authentication_strategies/remote.rb
spec/rails_helper.rb
spec/requests/sign_in_spec.rb
spec/requests/upload_spec.rb
spec/services/cognito/auth_user_spec.rb
spec/services/cognito/get_user_spec.rb
spec/support/mock_user.rb

https://eaflood.atlassian.net/browse/CAZB-98
Same as https://github.com/InformedSolutions/JAQU-CAZ-National-Taxi-Register-UI/pull/204/files

[CAZB-98] Add checking IP in the session

---

.drone.yml
package.json
yarn.lock

[NT] Add improved-yarn-audit

---

.drone.yml
package.json
yarn.lock

Update release v1.0.0 with yarn audit updates.

[NT] Add improved-yarn-audit (#70)

---

.drone.yml

fix missing awscli

---

app/views/accessibility_statement/index.html.haml
features/accessibility_statement.feature

[JIRA](https://eaflood.atlassian.net/browse/CAZB-343)

[CAZB-343] Update accessibility statement content

---

.github/PULL_REQUEST_TEMPLATE
Gemfile
Gemfile.lock
app/views/layouts/_cookies_banner.haml
package.json
yarn.lock

[NT] Update cookies banner and gem versions

---

app/views/accessibility_statement/index.html.haml

[JIRA](https://eaflood.atlassian.net/browse/CAZB-343)

[CAZB-343] Update accessibility page

---

.drone.yml

[NT] Update drone yml

---

.drone.yml

Adds ST pipeline steps to drone file.

Add ST pipeline steps

---

app/services/cognito/auth_user.rb
app/services/cognito/confirm_forgot_password.rb
app/services/cognito/forgot_password.rb
app/services/cognito/get_user.rb
app/services/cognito/respond_to_auth_challenge.rb
app/services/email_validator.rb
spec/requests/sign_in_spec.rb
spec/services/cognito/auth_user_spec.rb

[CAZB-491] Modify usernames are in lower case to use in Cognito

---

.env.development

[NT] Remove .env.development file

---

app/views/cookies/_cookie_control.html.haml
app/views/cookies/_seen_message.html.haml
app/views/cookies/index.html.haml

[JIRA](https://eaflood.atlassian.net/browse/CAZB-585)

[CAZB-585] Update cookies page

---

.drone.yml

fix for tests

---

Gemfile
Gemfile.lock
app/controllers/accessibility_statement_controller.rb
app/controllers/application_controller.rb
app/controllers/cookies_controller.rb
app/views/accessibility_statement/index.html.haml
app/views/cookies/_cookie_control.html.haml
app/views/cookies/_ga.html.haml
app/views/cookies/_session.html.haml
app/views/cookies/index.html.haml
app/views/layouts/_cookie_control.html.erb
config/application.rb
spec/api_wrappers/register_checker_api_spec.rb

[JIRA](https://eaflood.atlassian.net/browse/CAZB-639)

[CAZB-639] Content change to Retrofit Cookie Policy

---

app/views/layouts/_cookie_control.html.erb

https://eaflood.atlassian.net/browse/CAZB-740

[CAZB-740] Hide Control Cookie buttons and add `Save and close` button

---

config/environments/production.rb

[NT] Fix logs in production mode

---

.drone.yml

Update production URL for ecs checks

Update production URL for ecs checks

---

app/javascript/styles/cookie_control.scss
app/views/layouts/_cookie_control.html.erb
app/views/layouts/application.html.haml

https://eaflood.atlassian.net/browse/CAZB-1032

[CAZB-1032] Update CookieControl to version 9

---

app/views/layouts/application.html.haml
package.json
yarn.lock

Add the SRI hash to Cookie Control

---

.drone2.yml

Updated drone file for sonarqube execution

---

app/views/layouts/application.html.haml

https://eaflood.atlassian.net/browse/CAZB-1507

[CAZB-1511] Update check sum for Cookie Controller

---

.drone2.yml

Updated drone secrets and account name

---

.drone2.yml

updated drone file for controlled st environment

---

.drone2.yml

update account_name and ST env url

---

Dockerfile.build

Fix deploy with ECS Credentials check

---

.drone.yml

added tests to st deployment

---

.drone.yml
Dockerfile.build
config/initializers/amazon_s3.rb
config/initializers/aws_ses.rb

Ecs deploy changes

---

app/services/cognito/client.rb

Add Logs to Cognito::Client

---

app/services/cognito/client.rb

Add Logs to Cognito::Client - SecretManager result

---

app/services/cognito/client.rb

Fix/add getting Cognito credentials

---

app/services/cognito/client.rb
app/services/cognito/cognito_base_service.rb

Restore lost CAZB-1715 changes

---

app/services/cognito/client.rb

[CAZB-1863] Rotate Cognito Credentials on UnrecognizedClientException

---

.drone2.yml

Add SIT pipeline and pin docker images

Add SIT pipeline and pin docker images

---

.drone2.yml

Updated preprod deployment pipeline

---

.drone2.yml

updated drone changes for Prod environment

---

.drone2.yml

use the correct iam user and profile for aws calls for ecs rollout check

---

Dockerfile.build

Promote ECS fixes onto release baseline in new SIT

Alter variable allocation commands in Dockerfile

---

app/controllers/sessions_controller.rb
app/views/devise/sessions/new.html.haml
config/locales/devise.en.yml
config/locales/en.yml
config/routes.rb
features/password_reset.feature
features/sign_in.feature
features/step_definitions/force_password_change_steps.rb
features/upload.feature
lib/authentication_strategies/remote.rb
spec/requests/sign_in_spec.rb

https://eaflood.atlassian.net/browse/CAZB-1908

[CAZB-1908] Error message changes

---

app/helpers/application_helper.rb
app/models/new_password_form.rb
app/services/cognito/respond_to_auth_challenge.rb
app/views/passwords/new.html.haml
config/locales/en.yml
features/password_reset.feature
features/step_definitions/force_password_change_steps.rb
spec/models/new_password_form_spec.rb

Jira card: https://eaflood.atlassian.net/browse/CAZB-1943
Used the same NewPasswordForm as CS UI. 
Updated tests and views.

[CAZB-1943] Set up new password error messages

---

.drone2.yml

Updated UAT drone changes

---

app/services/cognito/forgot_password/confirm.rb
config/initializers/aws_custom_logger.rb

https://eaflood.atlassian.net/browse/CAZB-2093
Removed `Aws::CognitoIdentityProvider::Client` logging

[CAZB-2093] Fix "confirmation_code" leak in logs

---

app/views/accessibility_statement/index.html.haml

This change is required to update the broken link on the accessibility statement, to a mailing address for the IS support inboxes.
https://eaflood.atlassian.net/browse/CAZSM-65
Adjusted the content on the accessibility statement page to reflect sending an email with feedback as opposed to linking to a DVLA form.
rspec test -> Passed

updated accessibility feedback link to be an email

---

app/services/cognito/forgot_password/confirm.rb
app/views/accessibility_statement/index.html.haml
config/initializers/aws_custom_logger.rb

Update ST v1.4.0

---

.drone2.yml

migrate drone2 changes to develop branch

---

.drone2.yml

Updated st enviornment URL

---

.drone2.yml

updated sit, preprod, UAT URLs

---

.drone2.yml

Updated prod url

---

.drone.yml
.drone2.yml

https://eaflood.atlassian.net/browse/CAZB-2661
Updated env variable.

[CAZB-2661] Survey Link Update - Qualtrics (Production)

---

.drone2.yml

Added skip to yarn security audit until the fix is possible to deliver.

skip yarn audit advisory because of missing solution in webpackedr endency

---

app/views/passwords/confirm_reset.html.haml
app/views/passwords/new.html.haml
config/locales/en.yml

https://eaflood.atlassian.net/browse/CAZB-2327

[CAZB-2327] Update password policy

---

.drone2.yml

fixed var and password

---

app/views/upload/data_rules.html.haml
app/views/upload/index.html.haml
features/data_rules.feature

https://eaflood.atlassian.net/browse/CAZB-2729?focusedCommentId=242038
https://eaflood.atlassian.net/browse/CAZB-2734?focusedCommentId=242052
H1 width should be 100%
https://eaflood.atlassian.net/browse/CAZB-2729:
https://eaflood.atlassian.net/browse/CAZB-2734:

[CAZB-2729, 2734] Content changes

---

app/views/upload/data_rules.html.haml
app/views/upload/index.html.haml
features/data_rules.feature

Update RC with develop

---

Gemfile
Gemfile.lock

Bump Rails version to 6.0.3.4

---

.drone2.yml

[NON-JIRA] Exclude postcss from security check

---

app/controllers/sessions_controller.rb
app/forms/username_and_password.rb
app/views/devise/sessions/new.html.haml
config/environments/production.rb
config/i18n-tasks.yml
config/locales/en.yml
spec/forms/username_and_password_spec.rb
spec/requests/sign_in_spec.rb

[CAZB-4678] - Retrofit username enumeration fix

---

app/controllers/application_controller.rb
app/exceptions/referer_xss_exception.rb
app/javascript/packs/application.js
app/javascript/src/backLink/init.js
app/services/security/referer_xss_handler.rb
app/views/errors/service_unavailable.html.haml
app/views/shared/_js_back_link.html.haml
spec/services/security/referer_xss_handler_spec.rb

[CAZB-4676] - XSS referer header fix

---

.drone2.yml

[NON-JIRA] - Exclude from security tests

[NON-JIRA] - Exclude from security tests

---

.drone2.yml

* [NON-JIRA] - Exclude from security tests
* [NON-JIRA] Fix formatting
Co-authored-by: cruddasj <james.cruddas@informed.com>

[NON-JIRA] - Exclude from security tests (#390)

---

app/controllers/application_controller.rb
app/javascript/packs/application.js
app/javascript/src/backLink/init.js
app/views/errors/service_unavailable.html.haml
app/views/shared/_js_back_link.html.haml

Reverts InformedSolutions/JAQU-CAZ-Retrofit-UI#393

Revert "[CAZB-4676] Remove changes not needed for CAZB-4676"

---

.drone2.yml

Experiment: Drone upstream

---

.iyarc
yarn.lock

Security Test: http://drone-1587293244.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-Retrofit-UI/913/1/6

Bump yarn libs to fix Security tests

---

config/environments/production.rb
config/initializers/assets.rb

https://eaflood.atlassian.net/browse/CAZB-4829

[CAZB-4829] Add security headers to static assets served by Rails

---

.iyarc

[NON-JIRA] Fixed security test with exclusions

---

app/views/layouts/_cookie_control.html.erb
app/views/layouts/_gtm_script.html.erb
app/views/layouts/application.html.haml
config/initializers/content_security_policy.rb

[CAZB-4898] Update "unsafe-inline" CSP policy to use nonces

---

Gemfile
Gemfile.lock
app/api_wrappers/base_api.rb

Add ruby lib to fix loading gem in production mode.
https://www.rubydoc.info/gems/addressable/Addressable/URI

[CAZB-4196] Add addressable gem to Gemfile to load in production

---

.drone2.yml

[CAZB-4710] Lower domain switchover

[CAZB-4710] Lower domain switchover

---

app/controllers/application_controller.rb

[CAZB-5105] Change to flag Invalid Host Headers as 403 errors

---

.drone2.yml
app/controllers/application_controller.rb

Draft release candidate/v1.13.0

---

Gemfile.lock

Bump addressable to v2.8.0
